import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import { type ReactNode } from "react";
import { cookieToInitialState } from "wagmi";
import { Toaster } from "@/components/ui/sonner";
import { getConfig } from "../wagmi";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Wagmi",
	description: "Generated by create-wagmi",
};

export default async function RootLayout(props: { children: ReactNode }) {
	const headersList = await headers();
	const initialState = cookieToInitialState(
		getConfig(),
		headersList.get("cookie"),
	);
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${inter.className} dark`}>
				<Providers initialState={initialState}>{props.children}</Providers>
				<Toaster />
			</body>
		</html>
	);
}
