import { defineConfig } from "@wagmi/cli";
import { foundry, react, actions } from "@wagmi/cli/plugins";

export default defineConfig({
	out: "abis/generated.ts",
	contracts: [],
	plugins: [
		actions({
			getActionName: "legacy",
			overridePackageName: "@wagmi/core",
		}),
		foundry({
			project: "../../",
			artifacts: "out",
			forge: {
				clean: true,
				build: true,
				path: "~/.foundry/bin/forge",
				rebuild: true,
			},
			include: ["*.json"],
			exclude: [
				"00_DeployPoolManager.s.sol/**",
				"01_DeployHook.s.sol/**",
				"02_InitilizePool.s.sol/**",
				"03_AddLiquidity.s.sol/**",
				"BalanceDelta.sol/**",
				"Base.sol/**",
				"BaseHook.sol/**",
				"BeforeSwapDelta.sol/**",
				"BitMath.sol/**",
				"build-info",
				"console.sol/**",
				"CounterHook.t.sol/**",
				"Currency.sol/**",
				"CurrencyDelta.sol/**",
				"CurrencyReserves.sol/**",
				"CurrencySettler.sol/**",
				"CustomRevert.sol/**",
				"ERC20.sol/**",
				"ERC6909.sol/**",
				"ERC6909Claims.sol/**",
				"Extsload.sol/**",
				"Exttload.sol/**",
				"FFIHelper.sol/**",
				"FixedPoint128.sol/**",
				"FixedPoint96.sol/**",
				"FullMath.sol/**",
				"HookMiner.sol/**",
				"Hooks.sol/**",
				"IERC20Minimal.sol/**",
				"IERC6909Claims.sol/**",
				"IExtsload.sol/**",
				"IExttload.sol/**",
				"IHooks.sol/**",
				"IImmutableState.sol/**",
				"ImmutableState.sol/**",
				"IMulticall3.sol/**",
				"IPoolManager.sol/**",
				"IProtocolFees.sol/**",
				"IUnlockCallback.sol/**",
				"LiquidityMath.sol/**",
				"Lock.sol/**",
				"LPFeeLibrary.sol/**",
				"MockERC20.sol/**",
				"NoDelegateCall.sol/**",
				"NonzeroDeltaCount.sol/**",
				"Owned.sol/**",
				"ParseBytes.sol/**",
				"Pool.sol/**",
				"PoolId.sol/**",
				"PoolManager.sol/**",
				"Position.sol/**",
				"ProtocolFeeLibrary.sol/**",
				"ProtocolFees.sol/**",
				"SafeCast.sol/**",
				"safeconsole.sol/**",
				"Script.sol/**",
				"Slot0.sol/**",
				"SqrtPriceMath.sol/**",
				"StdAssertions.sol/**",
				"StdChains.sol/**",
				"StdCheats.sol/**",
				"StdError.sol/**",
				"StdInvariant.sol/**",
				"StdJson.sol/**",
				"StdMath.sol/**",
				"StdStorage.sol/**",
				"StdStyle.sol/**",
				"StdToml.sol/**",
				"StdUtils.sol/**",
				"SwapMath.sol/**",
				"Test.sol/**",
				"TickBitmap.sol/**",
				"TickMath.sol/**",
				"UnsafeMath.sol/**",
				"Vm.sol/**",
			],
		}),
	],
});
